- platform: mpd
  server: automation
  port: 6601
  location: Multi-Room Audio
- platform: mpd
  server: raspberrypi
  location: Bedroom
- platform: mpd
  server: automation
  location: Living Room
- platform: firetv
  host: localhost:5556
- platform: cast
  host: 192.168.1.13
