- platform: command_line
  switches:
    sound:
      oncmd: !env_var PC_SOUND_TOGGLE
      offcmd: !env_var PC_SOUND_TOGGLE
      initial: 'on'
    monitors:
      oncmd: !env_var PC_MONITORS_ON
      offcmd: !env_var PC_MONITORS_OFF
      initial: 'on'
- platform: mqtt
  name: "Sleeping"
  state_topic: "nfc/sleeping"
  command_topic: "nfc/sleeping"
  qos: 1
  payload_on: "yes"
  payload_off: "no"
  optimistic: false
  retain: true
- platform: mqtt
  name: "Detect Motion"
  state_topic: "nfc/detect_motion"
  command_topic: "nfc/detect_motion"
  qos: 1
  payload_on: "yes"
  payload_off: "no"
  retain: true
- platform: mqtt
  name: "Alert Motion"
  state_topic: "nfc/alert_motion"
  command_topic: "nfc/alert_motion"
  qos: 1
  payload_on: "yes"
  payload_off: "no"
  retain: true
- platform: mqtt
  name: "Presence"
  state_topic: "nfc/presence"
  command_topic: "nfc/presence"
  qos: 1
  payload_on: "yes"
  payload_off: "no"
  retain: true
- platform: mqtt
  name: "Nightlights"
  state_topic: "nfc/nightlights"
  command_topic: "nfc/nightlights"
  qos: 1
  payload_on: "yes"
  payload_off: "no"
  retain: true
- platform: mqtt
  name: "Vacation"
  state_topic: "nfc/vacation"
  command_topic: "nfc/vacation"
  qos: 1
  payload_on: "yes"
  payload_off: "no"
  retain: true
- platform: mqtt
  name: "Twitch"
  state_topic: "nfc/twitch"
  command_topic: "nfc/twitch"
  qos: 1
  payload_on: "yes"
  payload_off: "no"
  retain: true
- platform: mqtt
  name: "Cat Toy"
  state_topic: "switch/5/state"
  command_topic: "switch/5/state"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  retain: true
- platform: orvibo
  switches:
  - host: 192.168.1.12
    name: Smart Socket 1
  - host: 192.168.1.15
    name: Smart Socket 2
