# Conditions
- !include automation/sleep.yaml
- !include automation/wake.yaml
- !include automation/sunset.yaml
- !include automation/away.yaml
- !include automation/home.yaml
# Notifications
- !include automation/motion_notify.yaml
- !include automation/presence_notify.yaml
- !include automation/battery_notify.yaml
- !include automation/battery_notify_her.yaml
#- !include automation/twitch_notify.yaml
# Lights & Motion
- !include automation/bedroom_motion.yaml
- !include automation/bedroom_timer.yaml
- !include automation/bathroom_motion.yaml
- !include automation/bathroom_timer.yaml
- !include automation/craft_room_motion.yaml
- !include automation/craft_room_timer.yaml
- !include automation/living_room_motion.yaml
- !include automation/living_room_timer.yaml
