####################################################
#                                                  #
#                  Basic Settings                  #
#                                                  #
####################################################

###  Global configuration  ###
homeassistant:
  name: Home
  latitude: !env_var HOME_LATITUDE
  longitude: !env_var HOME_LONGITUDE
  temperature_unit: F
  time_zone: !env_var HASS_TIMEZONE
  customize: !include customized.yaml

###  Zones  ###
zone:
- name: Home
  latitude: !env_var HOME_LATITUDE
  longitude: !env_var HOME_LONGITUDE
  radius: 20
  icon: social:people
- name: Work
  latitude: !env_var WORK_LATITUDE
  longitude: !env_var WORK_LONGITUDE
  radius: 100

###  MQTT  ###
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: 6025
  keepalive: 60

###  HTTP  ###
http:
  api_password: !env_var HASS_API_PASSWORD

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

###  Devices  ###
device_tracker: !include devices/device_trackers.yaml
media_player: !include devices/media_players.yaml
camera: !include devices/cameras.yaml
switch: !include devices/switches.yaml
sensor: !include devices/sensors.yaml
light: !include devices/light.yaml

###  Logger  ###
logger: !include logger.yaml

###  Groups  ###
group: !include groups.yaml

###  Scenes  ###
scene: !include scenes.yaml

### Scripts ###
script: !include scripts.yaml

### Automation ###
automation: !include automation.yaml

### Notification ###
notify: !include notify.yaml

### Weblinks ###
weblink: !include weblink.yaml

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################

###  Sun  ###
sun:

###  Logbook  ###
logbook:

###  History  ###
history:

###  Frontend  ###
frontend:
