alias: Turn off lights when everyone leaves the house
trigger:
  platform: state
  entity_id: group.all_devices
  state: 'not_home'
condition:
- condition: state
  entity_id: switch.presence
  state: 'on'
action:
  service: light.turn_off
  entity_id: group.all_lights
