alias: Bathroom Motion - Lights Already On
trigger:
  platform: state
  entity_id: sensor.bedroom_motion
  state: 'yes'
condition:
  - platform: state
    entity_id: switch.detect_motion
    state: 'on'
  - platform: state
    entity_id: switch.nightlights
    state: 'on'
  - platform: state
    entity_id: light.bathroom
    state: 'on'
  - platform: state
    entity_id: switch.sleeping
    state: 'on'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5
action:
  service: homeassistant.turn_on
  entity_id: script.bathroom_restart_timer
