alias: Craft Room Motion - Lights Off
trigger:
  platform: state
  entity_id: sensor.craft_room_motion
  state: 'yes'
condition:
  - platform: state
    entity_id: switch.detect_motion
    state: 'on'
  - platform: state
    entity_id: light.craft_room
    state: 'off'
  - platform: state
    entity_id: switch.sleeping
    state: 'off'
action:
  service: homeassistant.turn_on
  entity_id: script.craft_room_start_timer
