alias: Craft Room Motion - Lights Already On
trigger:
  platform: state
  entity_id: sensor.craft_room_motion
  state: 'yes'
condition:
  - platform: state
    entity_id: switch.detect_motion
    state: 'on'
  - platform: state
    entity_id: light.craft_room
    state: 'on'
  - platform: state
    entity_id: switch.sleeping
    state: 'off'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5
action:
  service: homeassistant.turn_on
  entity_id: script.craft_room_restart_timer
