alias: Living Room Motion - Lights Off
trigger:
  platform: state
  entity_id: sensor.living_room_motion
  state: 'yes'
condition:
  - platform: state
    entity_id: switch.detect_motion
    state: 'on'
  - platform: state
    entity_id: light.living_room__hall
    state: 'off'
  - platform: state
    entity_id: switch.sleeping
    state: 'off'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5
action:
  service: homeassistant.turn_on
  entity_id: script.living_room_start_timer
