alias: Someone is home
trigger:
- platform: state
  entity_id: group.all_devices
  state: 'home'
condition:
- condition: state
  entity_id: switch.presence
  state: 'on'
- condition: state
  entity_id: device_tracker.her_phone
  state: 'not_home'
action:
  service: notify.notify
  data:
    message: Meredith is home
