alias: Turn on light when sun sets
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: !env_var SUNSET_ELEVATION
condition:
- condition: state
  entity_id: group.all_devices
  state: home
- condition: state
  entity_id: switch.vacation
  state: 'off'
action:
  service: homeassistant.turn_on
  entity_id: script.main_lights
