alias: Turn on light when sun sets
trigger:
  platform: numeric_state
  entity_id: sun.sun
  attribute: elevation
  below: -2
condition:
  platform: state
  entity_id: group.all_devices
  state: home
action:
  service: homeassistant.turn_on
  entity_id: script.main_lights
