#  Orvibo switches plug into standard wall ports
#  and provide remote turn on/off.

- platform: orvibo
  switches:
  - host: 192.168.1.12
    name: Smart Socket 1
  - host: 192.168.1.15
    name: Smart Socket 2
